apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fastapi-redis-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Krishnammraju3369/REDIS-K8S-LAB2.git
    targetRevision: HEAD
    path: charts/fastapi-redis
    helm:
      valueFiles:
        - ../../environments/dev/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
