apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fastapi-redis-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Krishnammraju3369/REDIS-K8S-LAB2.git
    targetRevision: HEAD
    path: fastapi-redis-chart/charts/fastapi-redis
    helm:
      valueFiles:
        - ../../environments/prod/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
