apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api 
spec:
  selector:
    app: python-api
  ports:
    - protocol: TCP
      port: {{ .Values.api.servicePort }}
      targetPort: {{ .Values.api.containerPort }}
  type: ClusterIP
